AWSTemplateFormatVersion: '2010-09-09'
Description: 'REST API for metasphere'

Parameters:
  ArticleBucketName:
    Description: 'Name of the article bucket'
    Type: 'String'
  MainTableArn:
    Description: 'ARN of the main DynamoDB table'
    Type: 'String'
  LogLevel:
    Description: 'Log level of Lmabda functions. "INFO" by default'
    Type: 'String'
    AllowedValues:
      - 'NOTSET'
      - 'DEBUG'
      - 'INFO'
      - 'WARNING'
      - 'ERROR'
      - 'CRITICAL'
    Default: 'INFO'
  ProjectTagValue:
    Description: 'Value to be associated with a "project" tag. "covid-19-research" by default'
    Type: 'String'
    Default: 'covid-19-research'

Resources:
  MetasphereApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref AWS::StackName
      Description: 'REST API for metashpere'
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTagValue

  # function that gets an article
  GetArticleFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: 'Gets an article associated with a given paper ID'
      Role: !GetAtt GetArticleFunctionRole.Arn
      Code: 'build/GetArticleFunction'
      Handler: 'index.lambda_handler'
      Runtime: 'python3.8'
      Timeout: 5
      Environment:
        Variables:
          MAIN_TABLE_ARN: !Ref MainTableArn
          ARTICLE_BUCKET_NAME: !Ref ArticleBucketName
          LOG_LEVEL: !Ref LogLevel
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTagValue
  # role to get from DynamoDB and S3
  GetArticleFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: 'Role to get from DynamoDB and S3'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: 'MainTableGet'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'dynamodb:GetItem'
                Resource:
                  - !Ref MainTableArn
        - PolicyName: 'ArticleBucketGet'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${ArticleBucketName}/*'
      Tags:
        - Key: 'project'
          Value: !Ref ProjectTagValue
  # role to invoke GetArticleFunction
  GetArticleFunctionInvokerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'apigateway.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'InvokeGetArticleFunction'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt GetArticleFunction.Arn

  # /article
  ArticleResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MetasphereApi
      ParentId: !GetAtt MetasphereApi.RootResourceId
      PathPart: 'article'

  # /article/{hash}
  ArticleHashResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MetasphereApi
      ParentId: !Ref ArticleResource
      PathPart: '{hash}'
  # - OPTIONS (for CORS support)
  ArticleHashOPTIONS:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      OperationName: 'Preflight for /article/{hash}'
      RestApiId: !Ref MetasphereApi
      ResourceId: !Ref ArticleHashResource
      HttpMethod: 'OPTIONS'
      AuthorizationType: 'NONE'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
      Integration:
        Type: 'MOCK'
        PassthroughBehavior: 'WHEN_NO_MATCH'
        RequestTemplates:
          application/json: >
            { "statusCode": 200 }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: '{}'
  # - GET
  ArticleHashGET:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      OperationName: 'Gets an article'
      RestApiId: !Ref MetasphereApi
      ResourceId: !Ref ArticleHashResource
      HttpMethod: 'GET'
      AuthorizationType: 'NONE'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
        - StatusCode: 400
        - StatusCode: 500
      Integration:
        Type: 'AWS'
        PassthroughBehavior: 'WHEN_NO_MATCH'
        # IntegrationHttpMethod must be POST for Lambda
        IntegrationHttpMethod: 'POST'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetArticleFunction.Arn}/invocations'
        Credentials: !GetAtt GetArticleFunctionInvokerRole.Arn
        RequestTemplates:
          application/json: |
            {
              "paperId": "$input.params('hash')"
            }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
          - StatusCode: 400
            SelectionPattern: '4\d{2}'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: |
                {
                  "statusCode": 400,
                  "message": "article is not available: hash=$input.params('hash')"
                }
          - StatusCode: 500
            SelectionPattern: '5\d{2}'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: |
                {
                  "statusCode": 500,
                  "message": "internal server error: hash=$input.params('hash')"
                }

Outputs:
  MetasphereApiId:
    Description: 'ID of the REST API'
    Value: !Ref MetasphereApi
    Export:
      Name: !Sub '${AWS::StackName}-id'
