AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'This SAM template is used only for building Lambda functions'

Resources:
  GetArticleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: 'get-article'
      Handler: 'index.lambda_handler'
      Runtime: 'python3.8'
